apiVersion: apps/v1
kind: Deployment
metadata:
  name: apilogger-app
  labels:
    app: apilogger-app
spec:
  selector:
    matchLabels:
      app: apilogger-app
  template:
    metadata:
      labels:
        app: apilogger-app
    spec:
      containers:
      - name: apilogger
        image: stenstromen/apilogger:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: apilogger-app
  labels:
    app: apilogger-app
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 31337
  selector:
    app: apilogger-app